import type { Metadata } from "next";
import "../globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "GOALS",
    description: "Generated by create next app",
    icons: {
        icon: "/assets/headerlogo.png", // Standard favicon
        apple: "/apple-touch-icon.png", // For iOS devices
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className={`${inter.className} antialiased`}>
            {children}
        </div>
    );
}
