import type { Metadata } from "next";
import "../globals.css";
import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "GOALS",
    description: "Generated by create next app",
    icons: {
        icon: "/assets/headerlogo.png", // Standard favicon
        apple: "/apple-touch-icon.png", // For iOS devices
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className={`${inter.className} antialiased`}>
            <ToastContainer position="top-right" autoClose={3000} />
            {children}
        </div>
    );
}
